FROM alpine:3.19

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && \
    apk add --no-cache bash coreutils gcc g++ musl-dev

RUN adduser -D judge && \
    mkdir -p /home/judge/workspace && \
    chown -R judge:judge /home/judge

USER judge
WORKDIR /home/judge

ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
